# services:
#   db-mongo:
#     image: mongo:6.0.6
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: 123456
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb:/data/db
#     expose:
#       - 27017

#   be-nest:
#     build:
#       context: .
#       dockerfie: Dockerfile
#     # restart: unless-stopped
#     environment:
#       - PORT=8989
#       - NODE_ENV=production
#       - MONGO_URL = mongodb://root:123456@mydb:27017/quangney?authSource=admin
#     expose:
#       - 8989
#     ports:
#       - "8089: 8089"

# volumes:
#   mongodb: # docker compose -p quangney-nest up -d

version: '3.8'

services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8989
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/quangney?authSource=admin
    expose:
      - "8989"
    ports:
      - "8089:8089"

volumes:
  mongodb:
